### PR TITLE
WIP - implement comments

### LINKED ISSUE #50: Add Lisp-style line comment syntax
- [ ] Lines starting with `;` should be comments

### PR DESCRIPTION
**Pull request by andrevidela**
fix #50

### CODE REVIEW

**Comment by andrevidela** [comment]
@clayrat Can you look at those tests? Can reproduce them on my machine on master. Is that normal?

**Comment by epost** [comment]
@andrevidela @clayrat should there be a PR based on https://github.com/typedefs/typedefs/tree/comments-fix instead?

**Comment by andrevidela** [comment]
Actually yes, I'm gonna do it right now

**Comment by andrevidela** [comment]
opened at #113, closing this one

**Pull request closed without merging**
