### PR TITLE
expose/reexport backends and term codec

### PR DESCRIPTION
**Pull request by epost**
@clayrat As far as I can see this PR is good to go. We do want the backend switch string Jelle mentioned yesterday, but we could do that in a separate PR.

### CODE REVIEW

**Comment by epost** [comment]
Oh drat, the build failed. :(

**Comment by clayrat** [comment]
Hm, somehow I missed one import. I guess I'll re do the backend function with a switch in this PR anyway, so we won't need that.

**Comment by clayrat** [comment]
Closes #49

**Comment by epost** [comment]
Fabuloso! Thanks @clayrat! 🌈

**Pull request merged**
