### PR TITLE
Split api

### PR DESCRIPTION
**Pull request by andrevidela**
Laying the groundwork for #143 and #206 

There shouldn't be anything too controversial here except choices about how to split up files and uses of re-exports

### CODE REVIEW

**Comment by clayrat** [comment]
Looks cool overall, although the distinction between `Data`, `Type` and `Term` is a bit confusing, should we maybe get rid of `Haskell.Data` and move the definitions into the other two?

**Comment by andrevidela** [comment]
What do you think or renaming `Type` and `Term` to `Typegen` and `Termgen` ?

What do you think about re-exporting `Haskell.Data` in `Haskell.Termgen` instead?

**Comment by andrevidela** [comment]
Wait, do we need to expose `Typegen`, `Termgen` and `Data` in the library? I assumed just having the generating functions would be enough

**Comment by andrevidela** [comment]
@clayrat ?

**Pull request merged**
